"""check schema

Revision ID: 3bc69bcf3b62
Revises: ea93a87aaf5c
Create Date: 2026-04-24 17:41:43.477529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc69bcf3b62'
down_revision = 'ea93a87aaf5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('ico',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('dic',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=34),
               nullable=True)
        batch_op.alter_column('bic',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('bic',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('iban',
               existing_type=sa.VARCHAR(length=34),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('zip_code',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('street',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('dic',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('ico',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###
