"""add offer number

Revision ID: a80def9f7df1
Revises: f243990c27b7
Create Date: 2026-05-31 14:14:04.492018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a80def9f7df1'
down_revision = 'f243990c27b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_clients')
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_column('offer_number')

    op.create_table('_alembic_tmp_clients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ico', sa.VARCHAR(length=20), nullable=True),
    sa.Column('dic', sa.VARCHAR(length=20), nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('zip_code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('country', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('iban', sa.VARCHAR(length=34), nullable=True),
    sa.Column('bic', sa.VARCHAR(length=11), nullable=True),
    sa.Column('is_vat_payer', sa.BOOLEAN(), nullable=True),
    sa.Column('ic_dph', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
