"""paymend method

Revision ID: 10ac8dd9271c
Revises: 128d9e2c4fb6
Create Date: 2025-08-16 22:32:33.942314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ac8dd9271c'
down_revision = '128d9e2c4fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.Enum('bank_transfer', 'cash', 'card', 'other', name='paymentmethod'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False))

    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
