"""invoice unique + pdf_path + counters

Revision ID: 128d9e2c4fb6
Revises: d23fadfd7594
Create Date: 2025-08-16 21:58:45.599235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '128d9e2c4fb6'
down_revision = 'd23fadfd7594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_path', sa.String(length=255), nullable=True))
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.Enum('unpaid', 'paid', 'canceled', name='invoicestatus'),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.create_unique_constraint('uq_user_invoice', ['user_id', 'invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_invoice', type_='unique')
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.Enum('unpaid', 'paid', 'canceled', name='invoicestatus'),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('pdf_path')

    # ### end Alembic commands ###
