"""empty message

Revision ID: 221dcc1803fb
Revises: 2f0b3fde8f63
Create Date: 2025-07-17 21:34:46.453716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221dcc1803fb'
down_revision = '2f0b3fde8f63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
