"""empty message

Revision ID: 783429fd642a
Revises: 
Create Date: 2025-07-12 20:41:35.970509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '783429fd642a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=False))
        batch_op.drop_column('total_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_price', sa.FLOAT(), nullable=False))
        batch_op.drop_column('total_cost')

    # ### end Alembic commands ###
