"""empty message

Revision ID: d23fadfd7594
Revises: 221dcc1803fb
Create Date: 2025-08-12 19:38:08.843844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23fadfd7594'
down_revision = '221dcc1803fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', name='invoicestatus'), nullable=False))
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
